#!/usr/bin/env bash
# project-launch.sh — Build a project and make it accessible via nginx at /apps/<slug>/
#
# Usage:
#   ./scripts/project-launch.sh <slug>               # build (if needed) + add nginx route
#   ./scripts/project-launch.sh <slug> --build-only  # build only, don't touch nginx
#   ./scripts/project-launch.sh <slug> --nginx-only  # add nginx route, skip build
#   ./scripts/project-launch.sh --list               # list served project apps
#
# Requirements:
#   - LAB env var (default: /home/lgiron/Lab)
#   - HUB_ROOT env var (default: $LAB/hub-ldom)
#   - Nginx reload: kill -HUP $(cat $HUB_ROOT/instances/ldom/logs/nginx.pid)

set -euo pipefail

LAB="${LAB:-/home/lgiron/Lab}"
HUB_ROOT="${HUB_ROOT:-${LAB}/hub-ldom}"
PROJECTS_DIR="${LAB}/project"
NGINX_PROJECTS_D="${HUB_ROOT}/instances/ldom/nginx/projects.d"
NGINX_PID="${HUB_ROOT}/instances/ldom/logs/nginx.pid"

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'

list_served() {
  echo -e "\n${BOLD}Served project apps:${NC}"
  if ls "${NGINX_PROJECTS_D}"/*.conf 2>/dev/null | head -1 > /dev/null 2>&1; then
    for f in "${NGINX_PROJECTS_D}"/*.conf; do
      slug=$(basename "$f" .conf)
      echo -e "  ${GREEN}✓${NC} /apps/${slug}/  →  ${f}"
    done
  else
    echo -e "  ${YELLOW}none yet${NC} — run: $0 <slug>"
  fi
  echo ""
  exit 0
}

usage() {
  echo "Usage: $0 <slug> [--build-only|--nginx-only]"
  echo "       $0 --list"
  exit 1
}

[[ "${1:-}" == "--list" ]] && list_served
[[ $# -lt 1 ]] && usage

SLUG="$1"
BUILD_ONLY=false
NGINX_ONLY=false
[[ "${2:-}" == "--build-only" ]] && BUILD_ONLY=true
[[ "${2:-}" == "--nginx-only" ]] && NGINX_ONLY=true

PROJECT_DIR="${PROJECTS_DIR}/${SLUG}"
if [[ ! -d "${PROJECT_DIR}" ]]; then
  echo -e "${RED}✗${NC} Project not found: ${PROJECT_DIR}"
  exit 1
fi

# ── Detect build output directory ──────────────────────────────────────────
detect_dist() {
  local slug="$1" dir="${PROJECTS_DIR}/$1"
  for candidate in dist out build public; do
    [[ -d "${dir}/${candidate}" ]] && echo "${dir}/${candidate}" && return
  done
  # Frontend subdir pattern (e.g. real-estate/frontend/dist)
  for sub in frontend src; do
    for candidate in dist out build; do
      [[ -d "${dir}/${sub}/${candidate}" ]] && echo "${dir}/${sub}/${candidate}" && return
    done
  done
  echo ""
}

# ── Detect build command ────────────────────────────────────────────────────
detect_build_cmd() {
  local dir="${PROJECTS_DIR}/$1"
  [[ -f "${dir}/package.json" ]] && grep -q '"build"' "${dir}/package.json" && { echo "npm run build"; return; }
  [[ -f "${dir}/frontend/package.json" ]] && grep -q '"build"' "${dir}/frontend/package.json" && { echo "cd frontend && npm run build"; return; }
  [[ -f "${dir}/Makefile" ]] && grep -q '^build' "${dir}/Makefile" && { echo "make build"; return; }
  echo ""
}

# ── Build step ──────────────────────────────────────────────────────────────
if [[ "${NGINX_ONLY}" != "true" ]]; then
  dist=$(detect_dist "${SLUG}")
  build_cmd=$(detect_build_cmd "${SLUG}")

  if [[ -n "${dist}" ]] && [[ -f "${dist}/index.html" ]]; then
    echo -e "${GREEN}✓${NC} Build already exists: ${dist}"
  elif [[ -n "${build_cmd}" ]]; then
    echo -e "${YELLOW}●${NC} Running build: cd '${PROJECT_DIR}' && ${build_cmd}"
    (cd "${PROJECT_DIR}" && eval "${build_cmd}")
    dist=$(detect_dist "${SLUG}")
    if [[ -z "${dist}" ]]; then
      echo -e "${RED}✗${NC} Build finished but no dist/ directory found."
      exit 1
    fi
    echo -e "${GREEN}✓${NC} Build done: ${dist}"
  else
    echo -e "${RED}✗${NC} No build command detected for '${SLUG}'."
    echo "  Add a 'build' script to package.json or create a Makefile with 'build' target."
    exit 1
  fi
else
  dist=$(detect_dist "${SLUG}")
  if [[ -z "${dist}" ]]; then
    echo -e "${RED}✗${NC} No dist directory found for '${SLUG}'. Build first."
    exit 1
  fi
fi

[[ "${BUILD_ONLY}" == "true" ]] && echo -e "${GREEN}✓${NC} Build-only done." && exit 0

# ── Generate nginx snippet ──────────────────────────────────────────────────
mkdir -p "${NGINX_PROJECTS_D}"
CONF_FILE="${NGINX_PROJECTS_D}/${SLUG}.conf"

cat > "${CONF_FILE}" << NGINX
        # Auto-generated by project-launch.sh — $(date -Iseconds)
        location = /apps/${SLUG} { return 301 /apps/${SLUG}/; }
        location /apps/${SLUG}/ {
            auth_request /_authelia_auth;
            alias ${dist}/;
            try_files \$uri \$uri/ /index.html =404;
            add_header Cache-Control "no-cache";
        }
NGINX

echo -e "${GREEN}✓${NC} Nginx snippet created: ${CONF_FILE}"

# ── Reload nginx ────────────────────────────────────────────────────────────
if [[ -f "${NGINX_PID}" ]]; then
  PID=$(cat "${NGINX_PID}")
  if kill -0 "${PID}" 2>/dev/null; then
    nginx -t -c "${HUB_ROOT}/instances/ldom/logs/nginx-generated.conf" 2>&1 && \
      kill -HUP "${PID}" && \
      echo -e "${GREEN}✓${NC} Nginx reloaded (PID ${PID})"
  else
    echo -e "${YELLOW}⚠${NC}  Nginx PID ${PID} not running — start nginx manually"
  fi
else
  echo -e "${YELLOW}⚠${NC}  No nginx PID file at ${NGINX_PID} — reload manually"
fi

echo ""
echo -e "${BOLD}Project '${SLUG}' is now served at:${NC}"
echo -e "  https://lab.dombot.tech/apps/${SLUG}/"
echo ""
